# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    max-http-post-size: -1
  port: 8082
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  freemarker:
    suffix: .html
    request-context-attribute: request

yanwo:
  cluster: false  #集群配置  true集群环境   false单机环境，还需打开pom.xml里的spring-session-data-redis注释
  globalSessionTimeout: 3600   #单机环境，session过期时间为60分钟
  redis:
    open: false  #是否开启redis缓存  true开启   false关闭

# 图片 ftp
ftp.host: 192.168.9.77
ftp.port: 21
ftp.user: ftpuser
ftp.password: 123456
#ftp.basePath: /home/www/images
ftp.basePath:
#sever.image.url: http://192.168.9.77:88
sever.image.url: https://yanwo-image.oss-cn-beijing.aliyuncs.com

# solr
solr.server.url: http://192.168.9.208:8081/solr
solr.server.reload.url: http://192.168.9.208:8081/solr/admin/cores?wt=json&action=RELOAD&core=collection1

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yanwo.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

#服务号的应用ID  微信H5内支付使用
app_id: wx53e0ce07db66b556
app_secret: c1e9b2c79cbc0a7e69f2fe363440d20b
#商户号1490295082 1509255961
MCH_ID: 1578482831
#API密钥
API_KEY: gp2ZUmAXc1I9RjCnZttYmyKKfE2TYySg

#公众号的应用ID  微信H5内支付使用
#app_id: wx7a855d5b2991ca2e
#app_secret: f092b15b5df2cc45f5c545f4fd35c655